"""empty message

Revision ID: 24d9bfa2628a
Revises: d2390547d93f
Create Date: 2019-06-20 16:08:32.621912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d9bfa2628a'
down_revision = 'd2390547d93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictor_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('predictor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictor_category_predictor_id'), 'predictor_category', ['predictor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictor_category_predictor_id'), table_name='predictor_category')
    op.drop_table('predictor_category')
    # ### end Alembic commands ###
