"""empty message

Revision ID: e6b6ef2a1868
Revises: 24d9bfa2628a
Create Date: 2019-07-16 10:15:14.410767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b6ef2a1868'
down_revision = '24d9bfa2628a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictor_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('collection_name', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('OK', 'FAILED', 'PENDING')"),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_predictor',
    sa.Column('pc_id', sa.Integer(), nullable=True),
    sa.Column('predictor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pc_id'], ['predictor_collection.id'], ),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictor.id'], )
    )
    op.add_column('user', sa.Column('first_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_login')
    op.drop_table('collection_predictor')
    op.drop_table('predictor_collection')
    # ### end Alembic commands ###
